# http://about.travis-ci.org/docs/user/languages/php/

language: php
php:
  - 5.3
  - 5.4
  - 5.5

services:
  - redis-server

install:
  - composer install
  - node -v
  - npm version
  - npm install bower
  - ./node_modules/.bin/bower install

before_script:
  - vendor/bin/codecept build
  - mysql -e 'create database myapp_test;'
  - php artisan --env=testing --database=mysql --seed migrate
  - php artisan --env=testing --database=mysql db:backup app/tests/_data/dump.sql

script:
  - vendor/bin/phpunit
  - vendor/bin/codecept run functional --steps --debug
